server:
  port: ${PORT:4000}

spring:
  application:
    name: hellotraveller-backend

  web:
    resources:
      static-locations: classpath:/static/

  jackson:
    default-property-inclusion: non_null

  datasource:
    url: jdbc:h2:mem:hellotraveller;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# CORS configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:*}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

amadeus:
  client:
    id: ${AMADEUS_KEY}
    secret: ${AMADEUS_SECRET}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  # redirect-uri: ${KAKAO_REDIRECT_URI} (Deprecated: Passed as param)

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
